### ISSUE TITLE
How to do face detection using Tensorflow js on the remote video tracks

### ISSUE THREAD

**Issue by Aayush795** [elizabethsiegle/twilioVideoWebChat9Mins#3]
Hi @elizabethsiegle , i have implemented and deployed your code, however i wanted to know if I can integrate this code for face detection in all the streams of the participants that join the room? basically something that sends the notification if the face goes out of frame..i wanted to use Tensorflow.js. is it possible? if yes, how do i access the video stream link?  Thanks
here is the link to tensorflow js
https://www.tensorflow.org/js/models

**Comment by elizabethsiegle** [comment]
Hi! You can detect that with TensorFlow.js! You need to import the model (I did this in a HTML file of a different project), grab the video element, and pass that to your model (PoseNet, BodyPix, or BlazeFace). I did this with PoseNet passing it `video`, but for BlazeFace it'd be something like this with `video` instead of `document.querySelector("img")`: https://github.com/tensorflow/tfjs-models/tree/master/blazeface

**Comment by Aayush795** [comment]
@elizabethsiegle but how would I apply the tf.js model on remote streams, I think one you mentioned would work on webcams based streams, right?
